### PR TITLE
Improve tests, part 2

### PR DESCRIPTION
**Pull request by Firgeis**
Add more tests

### CODE REVIEW

**Comment by Firgeis** [comment]
This seems to be an issue with threading an openssl v3, I try to set up some time to debug this

**Comment by Firgeis** [comment]
macOS test failure is caused by https://github.com/ocaml/opam/issues/5221.
Not sure if it's possible to fix @anmonteiro.

**Comment by anmonteiro** [comment]
We could try to set up a macOS runner for the nix tests. I've had success with that before. Let me try doing that in a separate PR.

**Comment by anmonteiro** [comment]
Tests seem to run well with Nix on macOS ([example run](https://github.com/savonet/ocaml-ssl/actions/runs/4934057361/jobs/8818648911), so I'm going to merge #111 and you can rebase.

**Comment by anmonteiro** [comment]
Thanks!

**Pull request merged**
