### PR TITLE
Refactor bindings to not use deprecated OpenSSL API

### PR DESCRIPTION
**Pull request by Lupus**
OpenSSL 1.1 deprecates the API calls that are used in ocaml-ssl.

I've looked how other projects do this transition in [grpc repo](https://github.com/grpc/grpc/pull/11496) and applied the same changes.

### CODE REVIEW

**Comment by Lupus** [comment]
We're using internally published fork with changes from this PR for a while already 🤷

**Comment by anmonteiro** [comment]
Do you have time to rebase it? I could pick it up otherwise.

**Comment by craff** [comment]
This PR is probably replaced by #115 ?

**Comment by anmonteiro** [comment]
#115 doesn't seem related to this PR? It still uses the old `{TLSV}_{client,server}_method` functions.

**Comment by craff** [comment]
You are right this is not the same. Latest openSSL is 3.1.1 not 1.1.1 so what to do is not really clear ?

**Comment by craff** [comment]
And 1.1.1 will be unsupported from 11th september 2023. OpenSSL is encouraging people to migrade to 3.0 or 3.1.

**Comment by anmonteiro** [comment]
IIRC OpenSSL 3 doesn't have new APIs: it drops 1.x deprecated APIs and includes security fixes. 

So if we migrate to these new APIs, as proposed in this PR, we'll stay compatible with both the 1.x and the 3.x release lines.

**Comment by craff** [comment]
But openssl 3 is not available in debian 11 (without recompilation from source). All this seems rather enoying.

**Comment by craff** [comment]
And openSSL 1.1.1 and 3.X drop support for TLsv 1.0 and 1.1 completely ?

**Comment by anmonteiro** [comment]
> But openssl 3 is not available in debian 11 (without recompilation from source). All this seems rather enoying.

Why is this a problem if we're staying 1.1 compatible?

**Comment by craff** [comment]
Antonio Nuno Monteiro writes:

>> But openssl 3 is not available in debian 11 (without recompilation from source). All this seems rather enoying.
>
> Why is this a problem if we're staying 1.1 compatible?

Wrote this before seeing your message that 3 and 1.1 are compatible.


--
Christophe Raffalli
tél: +689 87 23 11 48
web: http://raffalli.eu

Ce mail est signé avec pgp (Pièce jointe signature.asc, clef sur https://raffalli.eu/pgp)
This mail is signed pgp (Attachment signature.asc, clef on https://raffalli.eu/pgp)

**Comment by craff** [comment]
@anmonteiro, could you transform this PR into a branch so I can try to rebase it on master. I am not very confident with git ;-).

**Comment by anmonteiro** [comment]
@craff here are some instructions:

```shell
git remote add Lupus git@github.com:Lupus/ocaml-ssl.git
git fetch --all
git checkout --track Lupus/master
git checkout -b craff/my-own-branch
```

Then work in your `craff/my-own-branch` as usual.

**Comment by craff** [comment]
I did the rebase on master as #121. Was to easy, may be this hides a pb ?

**Comment by anmonteiro** [comment]
Thanks, this landed in #121

**Pull request closed without merging**
