### PR TITLE
work on error code: separate lib and reason

### PR DESCRIPTION
**Pull request by craff**
on 1.1.1, keep function code inside reason as it has been removed in 3.0

### CODE REVIEW

**Comment by Firgeis** [comment]
Looks good to me I will probably refactor the test helpers later to not parse the string since that was before we had these

**Comment by craff** [comment]
Did a small commit, I don't understant why 
`#if OPENSSL_VERSION_MAJOR < 3` could evaluate to true when the macro is undefined?

**Comment by Firgeis** [comment]
@craff I believe it is returning 0 because it is not defined but satisfies the comparison, we should test != 0 and < 3

**Comment by craff** [comment]
Ezequiel Lewin writes:

> @craff I believe it is returning 0 because it is not defined but satisfies the comparison, we should test != 0 and < 3

I replaced by #ifdef, much clearer.

--
Christophe Raffalli
tél: +689 87 23 11 48
web: http://raffalli.eu

Ce mail est signé avec pgp (Pièce jointe signature.asc, clef sur https://raffalli.eu/pgp)
This mail is signed with pgp (Attachment signature.asc, key  on  https://raffalli.eu/pgp)

**Comment by anmonteiro** [comment]
Thanks. I wanna rename the field names in the record, but I'll do that in a separate change.

**Pull request merged**
