### PR TITLE
Implement verification functions

### PR DESCRIPTION
**Pull request by Firgeis**
Adds a pair of verification functions that accept a parsed PEM certificate.
add_extra_chain_cert to send additional chain certs to the peer.
add_cert_to_store to allow verification of the peer certificate CA. This function combines libssl SSL_CTX_get_cert_store and X509_STORE_add_cert so as not to expose the internal store unnecessarily.
Also improves use_certificate_from_string to read any type of key instead of just RSA

### CODE REVIEW

**Comment by Firgeis** [comment]
@smimram Can I get this reviewd?

**Comment by EduardoRFS** [comment]
This is really desirable for platforms where the certs are outdated.

**Comment by EduardoRFS** [comment]
but @Firgeis I think you need to separate the branch there is additional commits besides of the ones mentioned by the PR

**Comment by Firgeis** [comment]
You are right but I think it is worth including and doesn't conflict with the others.
It's a function to verify the IP address in a SAN

**Pull request merged**
