### PR TITLE
Port build system to dune

### PR DESCRIPTION
**Pull request by rgrinberg**
As promised before, the release of dune makes #35 possible.

### CODE REVIEW

**Comment by andreypopp** [comment]
Glad to see this is being ported to dune, I'm having troubles building `ssl` under esy as the current build system handles `OCAMLFIND_LDCONF` supplying it an empty value by default or setting to `dummy` (instead of `ignore`) on `--disable-ldconf`.

**Comment by toots** [comment]
I'm cool with merging it. @smimram, any thought on it?

**Comment by smimram** [comment]
I have no strong objection against this (but I am not really sure about what this switch to dune would bring). In short, @toots I leave it up to you! ;)

**Comment by toots** [comment]
I'm not sure either, @smimram but I'm down to have the community help maintaining this package. Thanks for the feedback!

**Pull request merged**
