### PR TITLE
try to add dune runtest in workflow

### PR DESCRIPTION
**Pull request by craff**

### CODE REVIEW

**Comment by anmonteiro** [comment]
This is already done by `opam install -t`

**Comment by craff** [comment]
opam install -t did not detect the error in Ssl_com whle dune runtest is returning code 1

**Comment by craff** [comment]
I do this PR only to test if the the workflow fails now.

**Comment by anmonteiro** [comment]
It might be a problem with your installation of OpenSSL, or your version for it.

Tests are passing locally and on the Nix CI, which most definitely is running the tests.

**Comment by craff** [comment]
I seems that it does not. I don't understand. probably ssl_com is only failing on my machine ?

**Comment by craff** [comment]
I looked at the build details, it works. Iclose this PR and tries to see the problem on my machine.

**Pull request closed without merging**
