### PR TITLE
Correctly set #define's for ssl_stubs

### LINKED ISSUE #40: SSL: Method error with 0.5.6
Could be related to the switch to `dune`?

Minimal repro:

```
FROM ocaml/opam2:alpine-3.7-ocaml-4.06

RUN opam repo set-url default https://opam.ocaml.org && opam update
RUN sudo apk add --no-cache m4 pkgconf libressl-dev
RUN opam install ssl=0.5.6 cohttp-lwt-unix lwt_ssl
```

```
$ docker build . -t ssl-repro
...
$ docker run -it --rm ssl-repro cohttp-curl-lwt https://reddit.com
cohttp-curl: internal error, uncaught exception:
             SSL: Method error
```

Also reproducible on my OSX machine.

### PR DESCRIPTION
**Pull request by rgrinberg**
Fix #40

This will also require a dune release that includes: https://github.com/ocaml/dune/pull/1274

I will make it shortly

### CODE REVIEW

**Comment by rgrinberg** [comment]
Since dune 1.2.1 was released, this is now ready.

**Comment by Mishio595** [comment]
Bump

**Comment by smimram** [comment]
Thanks for the PR!

**Pull request merged**
